### ISSUE TITLE
Verify webpage background scrolls OK

### ISSUE THREAD

**Issue by mrawls** [dirac-institute/trailblazer#12]
Early website demo may have a glitchy scrolling background. Verify it doesn't look awful or load too slowly on different devices (computer, tablet, phone, etc.).

**Comment by Jedijoe100** [comment]
Is this still a thing on the current website design? If it is I don't seem to notice it.

**Comment by mrawls** [comment]
I haven't tested recently - @eggls6 originally noticed it for some devices/browsers. Maybe he can chime in. I lean toward keeping this open as a catch-all reminder to check for responsiveness (all pages loading smoothly on a variety of devices), but open to suggestions.

**Comment by mrawls** [comment]
Actually, the background is a stationary image now, so I'm closing this since it's not relevant. We can open a new issue for general responsiveness checking.

**Comment by eggls6** [comment]
Sorry, it is a bit late to chime in on that, but I think it was @DinoBektesevic who noticed some issues there. I didn't encounter any, to be frank, but I also have not tried what the page looks like on very different systems (windows/linux/macos/phones, etc.). No need to reopen.
