### ISSUE TITLE
Improve upload tool user interface

### ISSUE THREAD

**Issue by mrawls** [dirac-institute/trailblazer#24]
Right now, the upload tool lets a user select a single file from their computer and upload it. Some ideas for improvement

- Require that image to upload is a FITS file (fastest way to do this?)
- Ask user if the image already exists in an external archive we support, and suggest they link to that instead (TBD...)
- Add required fields for the user uploading the file to fill out, such as a checkbox agreeing the image is theirs or otherwise OK to share publicly, a checkbox agreeing to an appropriate creative commons license, and a valid contact email that won't be shared publicly (what else?)
- Handle multiple file uploads gracefully (what is a reasonable upper limit?)
- Show a progress bar during the upload process
- Display the uploaded image(s) when the upload completes, along with the metadata that will be added to the metadata database, with a note saying they should contact us if anything looks wrong

**Comment by DinoBektesevic** [comment]
Addressed in https://github.com/dirac-institute/trailblazer/pull/39. 
New requests can be opened in the future to address improvements..
