### ISSUE TITLE
Improve gallery appearance and functionality

### ISSUE THREAD

**Issue by mrawls** [dirac-institute/trailblazer#26]
The gallery shows thumbnail preview of all uploaded images. Improvements could include:

- Most of what appears on the gallery page ought to be images (not negative space)
- Thumbnail previews should ideally feature a portion of the image containing a satellite streak
- Make it possible for a user to hover or otherwise preview metadata for any image thumbnail
- Add ability to download the FITS files behind the thumbnail preview

**Comment by mrawls** [comment]
At the moment, the gallery shows a handful of pre-baked thumbnails; instead it ought to generate a thumbnail image (PNG or JPG, presumably?) from the uploaded FITS files.

Dino raised an excellent point: we would like the gallery to be expandable in a modular, object-oriented way so the codebase supports extending it later on. If you click on a picture, it loads a template, and maybe that template doesn't have much data in it now, but it could later hold some various scientific analysis information.

**Comment by mtbannister** [comment]
Other potential goals:
- clicking on a picture should either load a popup or a new page, showing both the streak portion thumbnail and the full-frame thumbnail
- ability to select multiple images within the gallery view for handing to the download option (may be a more friendly interface for some users than a table-view output)
